### ISSUE TITLE
missing dependency 'path_provider'

### ISSUE THREAD

**Issue by lexrus** [xperiafan13-rom/ShareImage-Flutter#1]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Users/lex/.pub-cache/git/ShareImage-Flutter-61d56984eb0a98004720f0166fdc0a836eb74c60/lib/share.dart
...refers, in an import, to the following library:
  package:path_provider/path_provider.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

**Comment by xellDart** [comment]
Im sorry, please try to add this to your pubspec.yaml https://pub.dev/packages/path_provider
